version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            cd src
            npm install

jobs:
  # CI build and run unit tests & linting
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps

      - run:
          name: Run linting
          command: |
            cd src
            mkdir -p test-output
            npm run test-lint

      - run:
          name: Run unit tests
          command: |
            cd src
            npm run test-unit

      - run:
          name: Generate code coverage reports
          command: |
            cd src
            npm run test-coverage

      - run:
          name: Validate code coverage
          command: |
            bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: ./src/test-output
      - store_artifacts:
          path: ./src/test-output
      - store_artifacts:
          path: ./src/coverage


  # Integration testing
  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: servian
    steps:
      - checkout
      - install_deps

      - run:
          name: Run integration tests
          command: |
            cd src
            mkdir -p test-output
            npm run test-integration

      - store_test_results:
          path: ./src/test-output
      - store_artifacts:
          path: ./src/test-output


  # E2E testing
  e2e-tests:
    docker:
      - image: circleci/node:lts-browsers
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: servian
    
    environment:
      QAW_HEADLESS: true
      LOGIN_USERNAME: postgres
      LOGIN_PASSWORD: password
    
    steps:
      - checkout
      - install_deps

      - run:
          name: Database migration
          command: |
            cd src
            node_modules/.bin/sequelize db:migrate
            
      - run: 
          name: Start the app in the background
          command: |
            cd src
            npm run start    
          background: true     
      
      - run:
          name: Run e2e tests
          command: |
            cd src
            npm run test-e2e

      - store_artifacts:
          path: ./src/qawolf


  # Packaging
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
      IMAGE_NAME: sdo-a1/building-on-ci
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest ./src
      
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME

      - store_artifacts:
          path: ./image.tar

workflows:
  version: 2
  build-test-package:
    jobs:
      - build
      - integration-tests:
          requires:
            - build
      - e2e-tests:
          requires:
              - integration-tests
      - pack:
          requires:
            - build
          filters:
            branches:
              only:
                - master
