version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            cd src
            npm install

jobs:
  # CI build and run unit tests & linting
  # Might need to add npm start
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps

      - run:
          name: Run linting
          command: |
            cd src
            mkdir -p test-output
            npm run test-lint

      - run:
          name: Run unit tests
          command: |
            cd src
            npm run test-unit

      - run:
          name: Generate code coverage reports
          command: |
            cd src
            npm run test-coverage

      - run:
          name: Validate code coverage
          command: |
            bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: ./src/test-output
      - store_artifacts:
          path: ./src/test-output

  # Static Code Analysis (SAST)
  sast:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install NodeJsScan
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
      - run:
          name: Run NodeJsScan
          command: |
            nodejsscan -d ./src -o sast-result.json
      - store_artifacts:
          path: sast-result.json
      - run:
          name: Parse SAST report
          command: |
            exit $(cat sast-result.json | jq .total_count.sec)

  # Integration testing
  # Change port APP_PORT to 3000
  # integration-tests:
  #   docker:
  #     - image: circleci/node:lts
  #     - image: mongo:4.0
  #   environment:
  #     APP_PORT: 3000
  #     JEST_JUNIT_OUTPUT_DIR: test-output
  #   steps:
  #     - checkout
  #     - install_deps
  #     - run:
  #         name: Run integration tests
  #         command: |
  #           mkdir -p test-output
  #           npm run test-integration
  #     - store_test_results:
  #         path: test-output


  # Packing
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - run: 
          name: Creating directory
          command: |
            cd src
            mkdir -p dist
      # - store_artifacts:
      #     path: ./src/dist

workflows:
  version: 2
  build-test-package:
    jobs:
      - build
      # - sast:
      #     requires:
      #       - build
      - pack:
          requires:
            - build
