version: "3"

services: 
  db:
    container_name: db
    image: postgres:9.6-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: servian
